### ISSUE TITLE
iOS Compatibility

### ISSUE THREAD

**Issue by patriciog** [CodeAndWeb/cocos2d-x-dynamic-lighting#1]
Hi @CodeAndWeb:

I'd like to know if this example code works fine with iOS or MAC. I'm seeing on **EffectSprite/Effect.h** this:

```
#if (CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID || CC_TARGET_PLATFORM == CC_PLATFORM_WP8 || CC_TARGET_PLATFORM == CC_PLATFORM_WINRT)
```

Thanks!

**Comment by CodeAndWeb** [comment]
Yes - it runs on iOS and Mac - we've developed it on a Mac ;-)
